export const categoryContainerKeys = [
  'VideoOnDemand',
  'VODStudio',
  'VODChildren',
  'VODTeenagers',
  'VODFamily',
  'VODProgramsEvents',
  'VODOurActivities',
  'VODMinistry',
  'VODOurOrganization',
  'VODBible',
  'VODMovies',
  'VODSeries',
  'VODMusicVideos',
  'VODIntExp',
  'VODAudioDescriptions',
  'Audio',
  'VOXBroadcasts',
  'ConvReleases'
] as const

export type CategoryContainerKey = (typeof categoryContainerKeys)[number]

export const categoryOnDemandKeys = [
  'AllVideos',
  'StudioFeatured',
  'StudioMonthlyPrograms',
  'StudioTalks',
  'StudioNewsReports',
  'BJF',
  'ChildrenSongs',
  'ChildrenMovies',
  'TeenSpiritualGrowth',
  'TeenSocialLife',
  'TeenGoals',
  'TeenWhatPeersSay',
  'TeenMovies',
  'FamilyChallenges',
  'FamilyDatingMarriage',
  'FamilyWorship',
  'FamilyMovies',
  'VODPgmEvtMorningWorship',
  'VODPgmEvtSpecial',
  'VODPgmEvtGilead',
  'VODPgmEvtAnnMtg',
  '2025Convention',
  '2024Convention',
  '2023Convention',
  '2022Convention',
  'VODActivitiesTranslation',
  'VODActivitiesAVProduction',
  'VODActivitiesPrintingShipping',
  'VODActivitiesConstruction',
  'VODActivitiesReliefWork',
  'VODActivitiesTheoSchools',
  'VODActivitiesSpecialEvents',
  'VODMinistryMidweekMeeting',
  'VODMinistryTools',
  'VODMinistryTeachings',
  'VODMinistryImproveSkills',
  'VODMinistryMethods',
  'VODMinistryExpandMinistry',
  'MeetingsConventions',
  'VODSampleConversations',
  'Reports',
  'VODOrgBethel',
  'AccomplishMinistry',
  'VODOrgHistory',
  'VODOrgLegal',
  'VODOrgBloodlessMedicine',
  'BibleBooks',
  'VODBibleReadingStudy',
  'VODBibleTeachings',
  'VODBibleAccounts',
  'VODBibleMedia',
  'VODBibleTranslations',
  'VODBiblePrinciples',
  'VODBibleCreation',
  'DramasGoodNews',
  'VODMoviesBibleTimes',
  'VODMoviesModernDay',
  'VODMoviesExtras',
  'VODMoviesAnimated',
  'VODMinistryApplyTeaching',
  'SeriesBJFSongs',
  'SeriesBJFLessons',
  'SeriesDigForTreasures',
  'SeriesLFFVideos',
  'SeriesBibleTeachings',
  'SeriesHappyMarriage',
  'SeriesImitateFaith',
  'SeriesBibleBooks',
  'SeriesIronSharpens',
  'SeriesJehovahsFriends',
  'SeriesLearnFromThem',
  'SeriesWTLessons',
  'VODLovePeople',
  'SeriesMyTeenLife',
  'SeriesNeetaJade',
  'SeriesOrgAccomplishments',
  'SeriesOurHistory',
  'VODPureWorshipIntro',
  'SeriesReasonsFaith',
  'SeriesBibleChangesLives',
  'SeriesGoodNews',
  'SeriesTruthTransforms',
  'SeriesOriginsLife',
  'SeriesWCGVideos',
  'SeriesWasItDesigned',
  'SeriesWebsiteAppHelp',
  'SeriesWhatPeersSay',
  'SeriesWhereAreTheyNow',
  'SeriesWhiteboard',
  'VODOriginalSongs',
  'VODSJJMeetings',
  'ChildrensSongs',
  'VODConvMusic',
  'MakingMusic',
  'VODSingToJah',
  'VODIntExpTransformations',
  'VODIntExpBlessings',
  'VODIntExpEndurance',
  'VODIntExpYouth',
  'OriginsLife',
  'VODIntExpArchives',
  'VODMidweekMeetingAD',
  'VODBiblePrinciplesAD',
  'SeriesBJFLessonsAD',
  'SeriesDigForTreasuresAD',
  'VODDramasAD',
  'VODLFFVideosAD',
  'VODSeriesBibleTeachingsAD',
  'VODFamilyAD',
  'SeriesHappyMarriageAD',
  'SeriesImitateFaithAD',
  'VODIntExpAD',
  'VODBibleBooksAD',
  'SeriesIronSharpensAD',
  'VODStudioAD',
  'SeriesJehovahsFriendsAD',
  'SeriesLearnFromThemAD',
  'SeriesWTLessonsAD',
  'VODLovePeopleAD',
  'SeriesMyTeenLifeAD',
  'OrgAccomplishmentsAD',
  'VODOriginalSongsAD',
  'VODOurActivitiesAD',
  'SeriesOurHistoryAD',
  'VODMinistryAD',
  'VODOurOrganizationAD',
  'VODProgramsEventsAD',
  'SeriesReasonsFaithAD',
  'VODSJJMeetingsAD',
  'VODTeenagersAD',
  'VODBibleAD',
  'SeriesBibleChangesLivesAD',
  'SeriesGoodNewsAD',
  'VODMinistryToolsAD',
  'VODIntExpTransformationsAD',
  'SeriesWCGVideosAD',
  'SeriesWhatPeersSayAD',
  'SeriesWhiteboardAD',
  '2025ConventionAD',
  '2024ConventionAD',
  '2023ConventionAD',
  '2022ConventionAD',
  '2021ConventionAD',
  '2020ConventionAD',
  '2019ConventionAD',
  '2016ConventionAD',
  'AudioOriginalSongs',
  'SJJMeetings',
  'SJJChorus',
  'SJJInstrumental',
  'Vocal',
  'AudioChildrenSongs',
  'KingdomMelodies',
  'FeaturedLibraryVideos',
  'FeaturedLibraryLanding',
  'FeaturedSetTopBoxes',
  'LatestVideos',
  'Other',
  'Satellite',
  'MidweekMeeting',
  'VOXDramaticBibleReading',
  'VOXDramas',
  'VOXBroadcasts2025',
  'VOXBroadcasts2024',
  'VOXBroadcasts2023',
  'VOXBroadcasts2022',
  'VOXBroadcasts2021',
  'VOXBroadcasts2020',
  'VOXBroadcasts2019',
  'VOXBroadcasts2018',
  'VOXBroadcasts2017',
  'VOXBroadcasts2016',
  'VOXBroadcasts2015',
  'VOXBroadcasts2014',
  'VOXGBUpdates',
  'ConvDay2',
  'ConvDay3',
  'TeachingToolbox',
  'FeaturedLibraryLandingUnpubLangs'
] as const

export type CategoryOnDemandKey = (typeof categoryOnDemandKeys)[number]

export const categoryTags = [
  'WebExclude',
  'RokuExclude',
  'JWLExclude',
  'FireTVExclude',
  'AppleTVExclude',
  'IncludeInJWORGAllVideosCatList',
  'RWLSExclude',
  'WWWExclude',
  'JWLCatalogExclude',
  'LibraryVideosExclude',
  'RokuCategorySelectionPosterScreen',
  'WebIncludeSubCategoriesInNav',
  'RokuCategoryGrid',
  'RWLSIncludeSubCategoriesAsNav',
  'WWWIncludeSubCategoriesAsNav',
  'ExcludeFromBreadcrumbs',
  'RokuCategoryGridScreen',
  'JWORGExclude',
  'RokuCategoryCarouselList',
  'StreamThisChannelEnabled',
  'WebFeatured',
  'PNRFeaturedLayout',
  'LimitToTwo',
  'AllowShuffleAsIconsInGrid',
  'AllowPlayAllAsIconsInGrid',
  'AllowShuffleInCategoryHeader',
  'AllowPlayAllInCategoryHeader',
  'SatelliteExclude',
  'RokuGridStyleSquare',
  'SuppressTopCategoryBanner',
  'WWWCatListExclude',
  'PreferSquareImages',
  'LimitToOne',
  'LimitToFive',
  'RokuMediaItemListScreen',
  'SearchExclude',
  'AllVideosExclude'
] as const

export type CategoryTag = (typeof categoryTags)[number]

export const mediaTags = [
  'JWORGExclude',
  'Month12',
  'Month11',
  'Month10',
  'Month09',
  'Month08',
  'Month07',
  'Month06',
  'Month05',
  'Month04',
  'Month03',
  'Month02',
  'Month01',
  'LatestVideosExclude',
  'AllVideosExclude',
  'WWWExclude',
  'WebExclude',
  'RokuExclude',
  'FireTVExclude',
  'AppleTVExclude',
  'SearchExclude',
  'SatelliteExclude',
  'RWLSExclude',
  'LibraryVideosExclude',
  'ConventionRelease',
  'JWLExclude',
  'JWLCatalogExclude'
] as const

export type MediaTag = (typeof mediaTags)[number]

export const clientTypes = [
  'appletv',
  'firetv',
  'JWORG',
  'none',
  'roku',
  'rwls',
  'satellite',
  'www'
] as const

export type ClientType = (typeof clientTypes)[number]

/**
 * The sizes of JW images. Sorted by priority.
 */
export const imageSizes = ['xl', 'lg', 'md', 'sm', 'xs'] as const

export type ImageSize = (typeof imageSizes)[number]

/**
 * The types of JW images. Sorted by priority.
 */
export const imageTypes = ['wsr', 'wss', 'lsr', 'lss', 'pnr', 'sqr', 'sqs', 'cvr'] as const

export type ImageType = (typeof imageTypes)[number]

export const publicationFileFormats = [
  '3GP',
  'AAC',
  'BRL',
  'DAISY',
  'EPUB',
  'JWPUB',
  'M4V',
  'MP3',
  'MP4',
  'PDF',
  'RTF',
  'ZIP'
] as const

export type PublicationFileFormat = (typeof publicationFileFormats)[number]

export const biblePublications = [
  'nwt',
  'nwtsty',
  'bi12',
  'int',
  'bi10',
  'bi22',
  'by',
  'rh'
] as const

export type BiblePublication = (typeof biblePublications)[number]
